// pdfExport.ts - two ways to generate PDFs:
// 1) exportSummaryReportPdf() - builds a report from scratch with jsPDF
// 2) exportElementAsPdf() - screenshots an HTML element and puts it in a PDF
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

// converts an image URL to base64 so we can embed it in the PDF
async function fetchImageAsBase64(url: string): Promise<string | null> {
  try {
    const res = await fetch(url, { mode: "cors" });
    const blob = await res.blob();
    return await new Promise<string>((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

// text wrapping with automatic page breaks
function wrapText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight: number,
): number {
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  for (const line of lines) {
    if (y > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, x, y);
    y += lineHeight;
  }
  return y;
}

// triggers the download in the browser
function downloadPdfBlob(doc: jsPDF, filename: string): void {
  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}


interface ExportOptions {
  from: string;
  to: string;
  generatedAt: string;
  reportText: string;
  chartUrls: string[];
}

// builds a full executive summary PDF with chart images and report text
export async function exportSummaryReportPdf(opts: ExportOptions): Promise<void> {
  const { from, to, generatedAt, reportText, chartUrls } = opts;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 14;
  const contentW = pageW - margin * 2;
  let y = 20;

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 41, 59);
  doc.text("WEAVE ERP Executive Summary Report", pageW / 2, y, { align: "center" });
  y += 10;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Date Range: ${from} — ${to}`, margin, y);
  y += 5;
  doc.text(`Generated: ${generatedAt}`, margin, y);
  y += 4;
  doc.setDrawColor(200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  const chartLabels = ["Weekly Rejection Rate", "Top 5 Defect Types", "Output vs Waste"];
  const chartW = (contentW - 6) / 3;
  const chartH = chartW * 0.75;

  const images = await Promise.all(chartUrls.map(fetchImageAsBase64));
  images.forEach((b64, i) => {
    if (!b64) return;
    const xPos = margin + i * (chartW + 3);
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(100);
    doc.text(chartLabels[i] ?? "", xPos + chartW / 2, y, { align: "center" });
    doc.addImage(b64, "PNG", xPos, y + 3, chartW, chartH);
  });

  y += chartH + 16;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 41, 59);
  doc.text("Executive Summary", margin, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60);

  const paragraphs = reportText.split(/\n/);
  for (const para of paragraphs) {
    if (para.trim() === "") {
      y += 3;
      continue;
    }
    y = wrapText(doc, para, margin, y, contentW, 4.5);
  }

  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(160);
    doc.text(`Page ${p} of ${totalPages}`, pageW / 2, doc.internal.pageSize.getHeight() - 6, { align: "center" });
    doc.text("Generated by WEAVE ERP", pageW - margin, doc.internal.pageSize.getHeight() - 6, { align: "right" });
  }

  const dateStamp = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  downloadPdfBlob(doc, `WEAVE_Executive_Summary_${dateStamp}.pdf`);
}

// screenshots an HTML element and drops it into a PDF (handles multi-page)
export async function exportElementAsPdf(
  element: HTMLElement,
  title: string,
): Promise<void> {
  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    backgroundColor: "#ffffff",
    logging: false,
  });

  const imgData = canvas.toDataURL("image/png");
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 10;
  const usableW = pageW - margin * 2;
  const headerH = 16;
  const footerH = 10;
  const usableH = pageH - headerH - footerH;

  const imgH = (canvas.height * usableW) / canvas.width;
  const totalPages = Math.max(1, Math.ceil(imgH / usableH));

  for (let page = 0; page < totalPages; page++) {
    if (page > 0) pdf.addPage();

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(30, 41, 59);
    pdf.text(title, pageW / 2, margin + 4, { align: "center" });
    pdf.setDrawColor(200);
    pdf.setLineWidth(0.3);
    pdf.line(margin, headerH - 1, pageW - margin, headerH - 1);

    const yOffset = headerH - page * usableH;
    pdf.addImage(imgData, "PNG", margin, yOffset, usableW, imgH);

    pdf.setFontSize(7);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(160);
    pdf.text(`Page ${page + 1} of ${totalPages}`, pageW / 2, pageH - 4, { align: "center" });
    pdf.text("Generated by WEAVE ERP", pageW - margin, pageH - 4, { align: "right" });
  }

  const safe = title.replace(/[^a-zA-Z0-9]/g, "_").substring(0, 40);
  const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  downloadPdfBlob(pdf, `WEAVE_${safe}_${stamp}.pdf`);
}
