// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using weave_erp_backend_api.Services;

#nullable disable

namespace weave_erp_backend_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305165041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("weave_erp_backend_api.Models.BillOfMaterials", b =>
                {
                    b.Property<int>("BOMID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BOMID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<decimal>("QtyRequired")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("VersionID")
                        .HasColumnType("int");

                    b.HasKey("BOMID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("VersionID");

                    b.ToTable("BillOfMaterials");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.BinLocation", b =>
                {
                    b.Property<int>("BinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BinID"));

                    b.Property<string>("BinCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<decimal>("Capacity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("BinID");

                    b.HasIndex("BinCode")
                        .IsUnique();

                    b.HasIndex("BranchID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("BinLocations");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Branch", b =>
                {
                    b.Property<int>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("BranchID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("RegionID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.BranchRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("RequestID");

                    b.HasIndex("BranchID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("RegionID");

                    b.HasIndex("RequestedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("BranchRequests");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.BranchRequestItem", b =>
                {
                    b.Property<int>("RequestItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestItemID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("QtyRequested")
                        .HasColumnType("int");

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("VersionID")
                        .HasColumnType("int");

                    b.HasKey("RequestItemID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("RequestID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("VersionID");

                    b.ToTable("BranchRequestItems");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Budget", b =>
                {
                    b.Property<int>("BudgetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetID"));

                    b.Property<bool>("AppliesToAll")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("BudgetCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<decimal>("LaborBudget")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MaterialsBudget")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OverheadBudget")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int?>("RegionID")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ReservedAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SpentAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubmittedByUserID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBudget")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<decimal>("WasteAllowanceBudget")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("BudgetID");

                    b.HasIndex("ApprovedByUserID");

                    b.HasIndex("BudgetCode")
                        .IsUnique();

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("RegionID");

                    b.HasIndex("SubmittedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.BudgetReservation", b =>
                {
                    b.Property<int>("BudgetReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetReservationID"));

                    b.Property<int>("BudgetID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<decimal>("LaborAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MaterialAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("OverheadAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("VersionID")
                        .HasColumnType("int");

                    b.HasKey("BudgetReservationID");

                    b.HasIndex("BudgetID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("VersionID");

                    b.ToTable("BudgetReservations");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Inspection", b =>
                {
                    b.Property<int>("InspectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspectionID"));

                    b.Property<string>("AQLLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("AcceptThreshold")
                        .HasColumnType("int");

                    b.Property<int>("BatchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("DefectsFound")
                        .HasColumnType("int");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectionLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RejectThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("SampleSize")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("InspectionID");

                    b.HasIndex("BatchID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("UserID");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Material", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("MaterialID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.MaterialInventory", b =>
                {
                    b.Property<int>("MatInvID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatInvID"));

                    b.Property<int>("BinID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialID")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("MatInvID");

                    b.HasIndex("BinID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("MaterialID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("MaterialInventories");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.MaterialTransaction", b =>
                {
                    b.Property<int>("MatTransID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatTransID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("MatInvID")
                        .HasColumnType("int");

                    b.Property<decimal>("QtyChanged")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MatTransID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("MatInvID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("UserID");

                    b.ToTable("MaterialTransactions");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("RegionID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("ApprovalStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("BranchID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductTransaction", b =>
                {
                    b.Property<int>("ProdTransID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdTransID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("ProdInvID")
                        .HasColumnType("int");

                    b.Property<decimal>("QtyChanged")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ProdTransID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("ProdInvID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("UserID");

                    b.ToTable("ProductTransactions");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductVersion", b =>
                {
                    b.Property<int>("VersionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersionID"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("BOMComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReleasedBudgetID")
                        .HasColumnType("int");

                    b.Property<decimal?>("StandardLaborCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("StandardOverheadCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VersionID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ReleasedBudgetID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("ProductVersions");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionBatch", b =>
                {
                    b.Property<int>("BatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchID"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("BatchQty")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ProducedDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("BatchID");

                    b.HasIndex("BatchNumber")
                        .IsUnique();

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("OrderID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("ProductionBatches");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionInventory", b =>
                {
                    b.Property<int>("ProdInvID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdInvID"));

                    b.Property<int>("BinID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("VersionID")
                        .HasColumnType("int");

                    b.HasKey("ProdInvID");

                    b.HasIndex("BinID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("VersionID");

                    b.ToTable("ProductionInventories");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionOrder", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("PlannedQty")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("VersionID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("BranchID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("VersionID");

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Region", b =>
                {
                    b.Property<int>("RegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("RegionID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("RegionName")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("RoleID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.RolePermissionChangeRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("RequestID");

                    b.HasIndex("BranchID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("RequestedByUserID");

                    b.HasIndex("ReviewedByUserID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("RolePermissionChangeRequests");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Transfer", b =>
                {
                    b.Property<int>("TransferID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromBinID")
                        .HasColumnType("int");

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("TransferID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("FromBinID");

                    b.HasIndex("RequestID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.TransferItem", b =>
                {
                    b.Property<int>("TransferItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferItemID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("QtyShipped")
                        .HasColumnType("int");

                    b.Property<int>("TransferID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("VersionID")
                        .HasColumnType("int");

                    b.HasKey("TransferItemID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("TransferID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("VersionID");

                    b.ToTable("TransferItems");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Middlename")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.HasIndex("BranchID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.BillOfMaterials", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.ProductVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.BinLocation", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Branch", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.BranchRequest", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.BranchRequestItem", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.BranchRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.ProductVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Budget", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.BudgetReservation", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.ProductVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Inspection", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.ProductionBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Material", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.MaterialInventory", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.BinLocation", null)
                        .WithMany()
                        .HasForeignKey("BinID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.MaterialTransaction", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.MaterialInventory", null)
                        .WithMany()
                        .HasForeignKey("MatInvID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Notification", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Product", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductTransaction", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.ProductionInventory", null)
                        .WithMany()
                        .HasForeignKey("ProdInvID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductVersion", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.Budget", null)
                        .WithMany()
                        .HasForeignKey("ReleasedBudgetID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionBatch", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.ProductionOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionInventory", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.BinLocation", null)
                        .WithMany()
                        .HasForeignKey("BinID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.ProductVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionOrder", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.ProductVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Region", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Role", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.RolePermissionChangeRequest", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Transfer", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.BinLocation", null)
                        .WithMany()
                        .HasForeignKey("FromBinID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.BranchRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.TransferItem", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.Transfer", null)
                        .WithMany()
                        .HasForeignKey("TransferID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.ProductVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.User", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
