// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using weave_erp_backend_api.Services;

#nullable disable

namespace weave_erp_backend_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309211214_AddAuditViewerTable")]
    partial class AddAuditViewerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("weave_erp_backend_api.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("RoleName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("AuditID");

                    b.HasIndex("PerformedAt");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.AuditViewer", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("DatePerformed")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAgent")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("EventID");

                    b.HasIndex("DatePerformed");

                    b.ToTable("AuditViewer", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.BillOfMaterials", b =>
                {
                    b.Property<int>("BOMID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BOMID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("QtyRequired")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("BOMID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("BillOfMaterials", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.BinLocation", b =>
                {
                    b.Property<int>("BinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BinID"));

                    b.Property<string>("BinLocationName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBinActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BinID");

                    b.HasIndex("BinLocationName")
                        .IsUnique();

                    b.ToTable("BinLocation", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Branch", b =>
                {
                    b.Property<int>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int?>("WarehouseManagerUserID")
                        .HasColumnType("int");

                    b.HasKey("BranchID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("WarehouseManagerUserID");

                    b.ToTable("Branch", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Budget", b =>
                {
                    b.Property<int>("BudgetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetID"));

                    b.Property<bool>("AppliesToAll")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("BudgetCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("CollectionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<decimal>("MaterialsBudget")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal>("ReservedAmount")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal>("SpentAmount")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubmittedByUserID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBudget")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<decimal>("WasteAllowanceBudget")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("BudgetID");

                    b.HasIndex("ApprovedByUserID");

                    b.HasIndex("BudgetCode")
                        .IsUnique();

                    b.HasIndex("CollectionID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("SubmittedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("Budget", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.CAPA", b =>
                {
                    b.Property<int>("CAPAID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CAPAID"));

                    b.Property<string>("CorrectiveAction")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InspectionID")
                        .HasColumnType("int");

                    b.Property<string>("IssueTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PreventiveAction")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ResponsibleDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ResponsibleUserID")
                        .HasColumnType("int");

                    b.Property<string>("RootCause")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("CAPAID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("InspectionID");

                    b.HasIndex("ResponsibleUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("CAPA", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Collection", b =>
                {
                    b.Property<int>("CollectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectionID"));

                    b.Property<string>("CollectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("TargetLaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("CollectionID");

                    b.HasIndex("CollectionCode")
                        .IsUnique();

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("Collection", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.CollectionBudgetPlan", b =>
                {
                    b.Property<int>("CollectionBudgetPlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectionBudgetPlanID"));

                    b.Property<string>("AdminDecision")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("AdminDecisionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdminDecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("BudgetCap")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.Property<decimal>("ContingencyPercent")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("SentToProductManager")
                        .HasColumnType("bit");

                    b.Property<bool>("SentToProductionManager")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("CollectionBudgetPlanID");

                    b.HasIndex("CollectionID")
                        .IsUnique();

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("CollectionBudgetPlan", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Inspection", b =>
                {
                    b.Property<int>("InspectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspectionID"));

                    b.Property<string>("AQLLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("AcceptThreshold")
                        .HasColumnType("int");

                    b.Property<int>("BatchBoardID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("DefectsFound")
                        .HasColumnType("int");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectionLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RejectThreshold")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("SampleSize")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("InspectionID");

                    b.HasIndex("BatchBoardID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("UserID");

                    b.ToTable("Inspection", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.InspectionChecklistResult", b =>
                {
                    b.Property<int>("ChecklistResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChecklistResultID"));

                    b.Property<string>("ChecklistStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ChecklistTemplateID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("InspectionID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("ChecklistResultID");

                    b.HasIndex("ChecklistTemplateID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("InspectionID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("InspectionChecklistResult", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.InspectionChecklistTemplate", b =>
                {
                    b.Property<int>("ChecklistTemplateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChecklistTemplateID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChecklistCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChecklistName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("ChecklistTemplateID");

                    b.HasIndex("ChecklistCode")
                        .IsUnique();

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("InspectionChecklistTemplate", (string)null);

                    b.HasData(
                        new
                        {
                            ChecklistTemplateID = 1,
                            Category = "Construction",
                            ChecklistCode = "CHK-STITCH",
                            ChecklistName = "Stitching quality",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = true,
                            SequenceNo = 1
                        },
                        new
                        {
                            ChecklistTemplateID = 2,
                            Category = "Material",
                            ChecklistCode = "CHK-FABRIC",
                            ChecklistName = "Fabric quality",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = true,
                            SequenceNo = 2
                        },
                        new
                        {
                            ChecklistTemplateID = 3,
                            Category = "Visual",
                            ChecklistCode = "CHK-COLOR",
                            ChecklistName = "Color consistency",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = true,
                            SequenceNo = 3
                        },
                        new
                        {
                            ChecklistTemplateID = 4,
                            Category = "Specification",
                            ChecklistCode = "CHK-MEASURE",
                            ChecklistName = "Measurement accuracy",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = true,
                            SequenceNo = 4
                        },
                        new
                        {
                            ChecklistTemplateID = 5,
                            Category = "Trims",
                            ChecklistCode = "CHK-LABEL",
                            ChecklistName = "Label and tag placement",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = true,
                            SequenceNo = 5
                        },
                        new
                        {
                            ChecklistTemplateID = 6,
                            Category = "Trims",
                            ChecklistCode = "CHK-BUTTON",
                            ChecklistName = "Button quality",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = true,
                            SequenceNo = 6
                        },
                        new
                        {
                            ChecklistTemplateID = 7,
                            Category = "Trims",
                            ChecklistCode = "CHK-ZIPPER",
                            ChecklistName = "Zipper functionality",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = true,
                            SequenceNo = 7
                        },
                        new
                        {
                            ChecklistTemplateID = 8,
                            Category = "Decoration",
                            ChecklistCode = "CHK-PRINT",
                            ChecklistName = "Print/embroidery quality",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = true,
                            SequenceNo = 8
                        },
                        new
                        {
                            ChecklistTemplateID = 9,
                            Category = "Finishing",
                            ChecklistCode = "CHK-CLEAN",
                            ChecklistName = "Cleanliness of garment",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = true,
                            SequenceNo = 9
                        },
                        new
                        {
                            ChecklistTemplateID = 10,
                            Category = "Finishing",
                            ChecklistCode = "CHK-THREAD",
                            ChecklistName = "Thread trimming",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = true,
                            SequenceNo = 10
                        },
                        new
                        {
                            ChecklistTemplateID = 11,
                            Category = "Final",
                            ChecklistCode = "CHK-OVERALL",
                            ChecklistName = "Overall appearance",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsRequired = true,
                            SequenceNo = 11
                        });
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.InspectionDefect", b =>
                {
                    b.Property<int>("InspectionDefectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspectionDefectID"));

                    b.Property<int>("AffectedQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("DefectCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DefectDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DefectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("InspectionID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SeverityScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("InspectionDefectID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("InspectionID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("InspectionDefect", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Material", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("MaterialID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("Material", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegionID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("UserID");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("ApprovalStatus")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("DesignNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ManufacturingInstructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SizeProfile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionBatchBoardItem", b =>
                {
                    b.Property<int>("BatchBoardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchBoardID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CollectionCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HandoffNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("ProductSKU")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("QAStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("QAStartedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("QAStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("RunCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScheduleKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BatchBoardID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("QAStartedByUserID");

                    b.ToTable("ProductionBatchBoardItem", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionInventory", b =>
                {
                    b.Property<int>("ProdInvID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdInvID"));

                    b.Property<int?>("BatchBoardID")
                        .HasColumnType("int");

                    b.Property<int>("BinID")
                        .HasColumnType("int");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReleaseTag")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("SourceInspectionID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("VersionID")
                        .HasColumnType("int");

                    b.HasKey("ProdInvID");

                    b.HasIndex("BatchBoardID");

                    b.HasIndex("BinID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SourceInspectionID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("VersionID");

                    b.ToTable("ProductionInventory", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionOrder", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Products")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderID");

                    b.HasIndex("OrderID", "VersionNumber");

                    b.ToTable("ProductionOrder", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionVersion", b =>
                {
                    b.Property<int>("VersionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersionID"));

                    b.Property<string>("CollectionCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VersionID");

                    b.HasIndex("CollectionID");

                    b.HasIndex("OrderID", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("ProductID", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ProductionVersion", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.HasKey("RoleID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("UpdatedByUserID");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.RunSchedule", b =>
                {
                    b.Property<int>("RunScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RunScheduleID"));

                    b.Property<string>("CollectionCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LineTeam")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LinkedVersion")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("OwnerAssignment")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("PlannedQty")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("ProductSKU")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("RunCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScheduleKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SizePlanJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RunScheduleID");

                    b.HasIndex("ScheduleKey")
                        .IsUnique();

                    b.ToTable("RunSchedule", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserID");

                    b.HasIndex("BranchID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UpdatedByUserID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.BillOfMaterials", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Branch", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("WarehouseManagerUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Budget", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.CAPA", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.Inspection", null)
                        .WithMany()
                        .HasForeignKey("InspectionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ResponsibleUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Collection", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.CollectionBudgetPlan", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Inspection", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.ProductionBatchBoardItem", null)
                        .WithMany()
                        .HasForeignKey("BatchBoardID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.InspectionChecklistResult", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.InspectionChecklistTemplate", null)
                        .WithMany()
                        .HasForeignKey("ChecklistTemplateID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.Inspection", null)
                        .WithMany()
                        .HasForeignKey("InspectionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.InspectionChecklistTemplate", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.InspectionDefect", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.Inspection", null)
                        .WithMany()
                        .HasForeignKey("InspectionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Material", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Notification", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Product", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionBatchBoardItem", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("QAStartedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionInventory", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.ProductionBatchBoardItem", null)
                        .WithMany()
                        .HasForeignKey("BatchBoardID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.BinLocation", null)
                        .WithMany()
                        .HasForeignKey("BinID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.Inspection", null)
                        .WithMany()
                        .HasForeignKey("SourceInspectionID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.ProductionVersion", null)
                        .WithMany()
                        .HasForeignKey("VersionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionOrder", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.ProductionVersion", null)
                        .WithMany()
                        .HasForeignKey("OrderID", "VersionNumber")
                        .HasPrincipalKey("OrderID", "VersionNumber")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.ProductionVersion", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.ProductionOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.Role", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("weave_erp_backend_api.Models.User", b =>
                {
                    b.HasOne("weave_erp_backend_api.Models.Branch", null)
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("weave_erp_backend_api.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("weave_erp_backend_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserID")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
